--- #YAML:1.0
name:               Chess-PGN-Moves
version:            0.05
abstract:           Perl extension for tabular data in support of Chess::PGN::EPD
author:
    - A. U. Thor <a.u.thor@a.galaxy.far.far.away>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
